# Generated by Django 6.0.1 on 2026-01-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=100)),
                ('food_description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('expiry_time', models.DateTimeField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('is_claimed', models.BooleanField(default=False)),
            ],
        ),
    ]
