# Generated by Django 6.0.1 on 2026-01-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodpost',
            name='food_description',
        ),
        migrations.AddField(
            model_name='foodpost',
            name='food_item',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
